### PR TITLE
chore: update readme minimum laravel version

### PR DESCRIPTION
**Pull request by atymic**
As per https://github.com/spatie/laravel-image-optimizer/issues/65 the supported version in the readme is incorrect.

I have updated it as per the current `composer.json` :smile:

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you (also for work you do on our other repos 👍 )

**Comment by atymic** [comment]
No worries :smile: 
Was there a reason this was not merged? (as the README is still wrong)?
Thanks!

**Comment by freekmurze** [comment]
Whoops, pressed the wrong button. It’s now merged.

**Comment by atymic** [comment]
No worries :smile:

**Pull request merged**
